# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

np.random.rand(3,3,3)

array([[[0.62571215, 0.52698935, 0.51464971],
        [0.90428998, 0.45250424, 0.58603695],
        [0.4280628 , 0.53960374, 0.49403581]],

       [[0.96299888, 0.40724307, 0.2880948 ],
        [0.22499548, 0.06536699, 0.56791207],
        [0.41422059, 0.89306889, 0.70758667]],

       [[0.99892354, 0.68203966, 0.48093501],
        [0.74305185, 0.21516347, 0.91072052],
        [0.32479355, 0.64540557, 0.62963207]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
a = np.ones((8,8))
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 4. Normalize a 5x5 random matrix

In [4]:
a    = np.random.random((5, 3))
_max = a.max()
_min = a.min()
(a - _min) / (_max - _min)

array([[0.1291348 , 0.39148268, 0.88264384],
       [0.98228433, 0.32285611, 0.69370245],
       [0.39057496, 0.5057843 , 0.34279175],
       [0.        , 1.        , 0.6089875 ],
       [0.29904344, 0.93583743, 0.2947867 ]])

# 5.  How to find common values between two arrays?

In [5]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,1]])
np.intersect1d(a1, a2)

array([1, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
print("Date yesterday:", np.datetime64('today') - np.timedelta64(1, 'D'))
print("Date today    :", np.datetime64('today'))
print("Date tomorrow :", np.datetime64('today') + np.timedelta64(1, 'D'))

Date yesterday: 2020-07-25
Date today    : 2020-07-26
Date tomorrow : 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
a1 = np.random.rand(3,3)
a2 = np.random.rand(3,3)
np.array_equal(a1,a2)

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
a = np.random.rand(10)
a[a == a.max()] = 0
a

array([0.41717892, 0.60542486, 0.81150635, 0.40815675, 0.44860778,
       0.25292251, 0.00157143, 0.73039941, 0.65716079, 0.        ])

# 9. How to print all the values of an array?

In [9]:
a = np.random.rand(2,2,2)

for i in a.flatten():
    print(i)

0.25063844822020553
0.9559566553762621
0.9851882271533368
0.830307255328675
0.3489726357391738
0.4895505040737391
0.7882557081439852
0.9417166072709375


# 10.Subtract the mean of each row of a matrix

In [10]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a - np.mean(a, axis=1)

array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
a = np.random.rand(10)
b = np.array([0,2,2,9])
a[np.bincount(b) != 0] += 1
a

array([1.4818328 , 0.93004638, 1.83932274, 0.09948546, 0.80195761,
       0.5396722 , 0.58803985, 0.86972983, 0.5048371 , 1.0102217 ])

# 12.How to get the diagonal of a dot product?

In [12]:
# https://stackoverflow.com/questions/14758283/is-there-a-numpy-scipy-dot-product-calculating-only-the-diagonal-entries-of-the
a = np.random.rand(50, 10)
b = np.random.rand(10, 10)
np.einsum('ij,jk,ki->i', a, b, a.T)

array([10.86634245,  9.13031304, 14.46084415,  8.21691389, 10.61220364,
       12.1928199 ,  8.95460964, 14.93458011,  7.3943196 ,  8.60885485,
       16.3505845 ,  6.935117  ,  7.44718899, 18.6971573 ,  9.7686984 ,
       10.59864292, 17.06238292,  8.34413143, 21.56659674, 10.34248068,
        7.8752488 , 18.028211  , 22.44751306, 13.77622356, 18.11019836,
        8.99838985, 18.41325263,  8.79786676,  9.41556861, 15.38757711,
       19.35754586, 15.78874594,  6.25968699,  9.95292022, 12.51028514,
       16.90587978,  8.77837661, 11.14024111,  8.88586896,  6.72869736,
       14.07982752, 13.1901583 ,  9.91631386,  8.2580407 , 11.03368835,
       19.6291388 ,  8.16907752, 12.8167471 , 11.38195137, 16.93046284])

# 13.How to find the most frequent value in an array?

In [13]:
a = np.array([1,2,2,3,4,1,2])

values, count = np.unique(a, return_counts=True)
values[np.argmax(count)]

2

# 14.How to get the n largest values of an array

In [14]:
n = 5
a = np.random.rand(3,3,3)
sorted(a.flatten())[-n-1:-1]

[0.6988665918936943,
 0.8171836340364698,
 0.9185992195867856,
 0.9759654843321034,
 0.9842219906559604]

# 15.How to create a record array from a regular array?

In [15]:
a = np.random.rand(6,3)
a

array([[0.15888758, 0.9941708 , 0.15535306],
       [0.54721881, 0.87065346, 0.60064457],
       [0.06781745, 0.67603192, 0.42992684],
       [0.52795648, 0.63447063, 0.97550715],
       [0.22539639, 0.25139329, 0.4199564 ],
       [0.72090754, 0.64271803, 0.98188387]])

In [16]:
# # https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-190.php
r = np.core.records.fromarrays(a.T)
r

rec.array([(0.15888758, 0.9941708 , 0.15535306),
           (0.54721881, 0.87065346, 0.60064457),
           (0.06781745, 0.67603192, 0.42992684),
           (0.52795648, 0.63447063, 0.97550715),
           (0.22539639, 0.25139329, 0.4199564 ),
           (0.72090754, 0.64271803, 0.98188387)],
          dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8')])

In [17]:
r.f0

array([0.15888758, 0.54721881, 0.06781745, 0.52795648, 0.22539639,
       0.72090754])